service: employees-api

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'